package dotty.tools.doc.client

import scala.scalajs.{ js => sjs }
import sjs.JSConverters._
import sjs.Dynamic.global
import sjs.JSApp
import sjs.annotation.JSName

/** The unpickled AST available as scala classes */
object EntityIndex {
  import model._

  lazy val packages: Map[String, Package] =
    Index.packages.toMap[String, Package]

  val currentEntity: Entity = Index.currentEntity

  /** Unparsed index stores the pickled AST generated by the dottydoc tool */
  @sjs.native @JSName("Index") private object Index extends sjs.Object {
    def packages: sjs.Dictionary[Package] = sjs.native
    def currentEntity: Entity = sjs.native
  }
}
